// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmhiUJFclMCnrQnH4PSDU3GfPWbJV68s',
    appId: '1:242515449502:web:b130cfb1461d669072cd8f',
    messagingSenderId: '242515449502',
    projectId: 'blocpattern-1e480',
    authDomain: 'blocpattern-1e480.firebaseapp.com',
    storageBucket: 'blocpattern-1e480.appspot.com',
    measurementId: 'G-TKPXVWJV7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8F04dOvEZ1PXOQK_or0o7fve_p5zdMU',
    appId: '1:242515449502:android:626d5bf41c49d3bf72cd8f',
    messagingSenderId: '242515449502',
    projectId: 'blocpattern-1e480',
    storageBucket: 'blocpattern-1e480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAloMwuy9RqSKmdbo6p2LNjjVaBZBKqL9U',
    appId: '1:242515449502:ios:bc9a0ace28aedcfa72cd8f',
    messagingSenderId: '242515449502',
    projectId: 'blocpattern-1e480',
    storageBucket: 'blocpattern-1e480.appspot.com',
    iosClientId: '242515449502-sbi4s1q0ahic05gbaqno9pcihm98tb6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocPattern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAloMwuy9RqSKmdbo6p2LNjjVaBZBKqL9U',
    appId: '1:242515449502:ios:4b0a3d6a48180e7372cd8f',
    messagingSenderId: '242515449502',
    projectId: 'blocpattern-1e480',
    storageBucket: 'blocpattern-1e480.appspot.com',
    iosClientId: '242515449502-rbn04vcilugu2h8a5fb8eiiatri8h19j.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocPattern.RunnerTests',
  );
}
